version: "2"

linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocognit
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    govet:
      enable:
        - shadow
    gocognit:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 2
    misspell:
      locale: US
    lll:
      line-length: 120
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
    revive:
      rules:
        - name: var-naming
          severity: warning
          disabled: false
          arguments:
            - - "ID"
              - "API"
              - "HTTP"
              - "JSON"
              - "URL"
              - "XML"
              - "YAML"
              - "ARN"
        - name: exported
          severity: warning
          disabled: false
          arguments:
            - "checkPrivateReceivers"
            - "sayRepetitiveInsteadOfStutters"
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code
        - name: redefines-builtin-id
  exclusions:
    paths:
      - vendor
    rules:
      - path: '_test\.go'
        linters:
          - mnd
          - gocognit
          - goconst
          - gosec
          - lll
          - gocritic
          - gochecknoinits
          - unused
          - errcheck
          - staticcheck
          - govet
          - whitespace
          - revive

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/AltairaLabs/promptarena-deploy-agentcore
  exclusions:
    paths:
      - vendor

run:
  timeout: 5m
  tests: false

output:
  formats:
    text:
      colors: true
      print-issued-lines: true
      print-linter-name: true
