# GoReleaser configuration for promptarena-deploy-agentcore
# See: https://goreleaser.com

version: 2

builds:
  - id: promptarena-deploy-agentcore
    binary: promptarena-deploy-agentcore
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/AltairaLabs/promptarena-deploy-agentcore/internal/agentcore.Version={{.Version}}
      - -X github.com/AltairaLabs/promptarena-deploy-agentcore/internal/agentcore.Commit={{.Commit}}
      - -X github.com/AltairaLabs/promptarena-deploy-agentcore/internal/agentcore.Date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: AltairaLabs
    name: promptarena-deploy-agentcore
  draft: true
  name_template: "promptarena-deploy-agentcore {{.Version}}"
